# -*- makefile-gmake -*-

###########################
## Package configuration ##
###########################
.PHONY: all

all: all-generic

AUTHORS  = $(shell cat AUTHORS | tr '\n' ',' | cut -d, -f1,4 | tr ',' '-')

VERSION	  = 0.1
TARGET	  = blacs
TARGETEXT = blacs
PACKAGE	  = blacs-$(AUTHORS)-$(VERSION)
